package edu.poly.common;

//enum là 1 kiểu dl dạng liệt kê cho phép liệt kê các hàng
public enum PageType {
	USER_MANAGEMENT_PAGE,REPORT_MANAGEMENT_PAGE,VIDEO_MANAGEMENT_PAGE,
	SITE_HOME_PAGE,SITE_LOGIN_PAGE,SITE_REGISTATION_PAGE,
	SITE_CHANGE_PASSWORD_PAGE,SITE_EDIT_PROFILE_PAGE,SITE_FORGOT_PASSWORD_PAGE,
	SITE_DETAIL_PAGE,SITE_FAVORITE_PAGE,SITE_SHARE_PAGE,HOME_MANAGEMENT_PAGE
}
